// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: rpc.proto

package rpcconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	rpc "github.com/jbarzegar/ron-mod-manager/rpc"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// RPCName is the fully-qualified name of the RPC service.
	RPCName = "rpc.RPC"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// RPCInstallArchiveProcedure is the fully-qualified name of the RPC's InstallArchive RPC.
	RPCInstallArchiveProcedure = "/rpc.RPC/InstallArchive"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	rPCServiceDescriptor              = rpc.File_rpc_proto.Services().ByName("RPC")
	rPCInstallArchiveMethodDescriptor = rPCServiceDescriptor.Methods().ByName("InstallArchive")
)

// RPCClient is a client for the rpc.RPC service.
type RPCClient interface {
	// Emits event to have core install a zip file as an archive
	InstallArchive(context.Context, *connect.Request[rpc.InstallArchiveRequest]) (*connect.Response[rpc.InstallArchiveReply], error)
}

// NewRPCClient constructs a client for the rpc.RPC service. By default, it uses the Connect
// protocol with the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed
// requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewRPCClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) RPCClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &rPCClient{
		installArchive: connect.NewClient[rpc.InstallArchiveRequest, rpc.InstallArchiveReply](
			httpClient,
			baseURL+RPCInstallArchiveProcedure,
			connect.WithSchema(rPCInstallArchiveMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// rPCClient implements RPCClient.
type rPCClient struct {
	installArchive *connect.Client[rpc.InstallArchiveRequest, rpc.InstallArchiveReply]
}

// InstallArchive calls rpc.RPC.InstallArchive.
func (c *rPCClient) InstallArchive(ctx context.Context, req *connect.Request[rpc.InstallArchiveRequest]) (*connect.Response[rpc.InstallArchiveReply], error) {
	return c.installArchive.CallUnary(ctx, req)
}

// RPCHandler is an implementation of the rpc.RPC service.
type RPCHandler interface {
	// Emits event to have core install a zip file as an archive
	InstallArchive(context.Context, *connect.Request[rpc.InstallArchiveRequest]) (*connect.Response[rpc.InstallArchiveReply], error)
}

// NewRPCHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewRPCHandler(svc RPCHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	rPCInstallArchiveHandler := connect.NewUnaryHandler(
		RPCInstallArchiveProcedure,
		svc.InstallArchive,
		connect.WithSchema(rPCInstallArchiveMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/rpc.RPC/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case RPCInstallArchiveProcedure:
			rPCInstallArchiveHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedRPCHandler returns CodeUnimplemented from all methods.
type UnimplementedRPCHandler struct{}

func (UnimplementedRPCHandler) InstallArchive(context.Context, *connect.Request[rpc.InstallArchiveRequest]) (*connect.Response[rpc.InstallArchiveReply], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rpc.RPC.InstallArchive is not implemented"))
}
