// Code generated by ent, DO NOT EDIT.

package pak

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the pak type in the database.
	Label = "pak"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldInstalled holds the string denoting the installed field in the database.
	FieldInstalled = "installed"
	// EdgeMod holds the string denoting the mod edge name in mutations.
	EdgeMod = "mod"
	// Table holds the table name of the pak in the database.
	Table = "paks"
	// ModTable is the table that holds the mod relation/edge.
	ModTable = "paks"
	// ModInverseTable is the table name for the Mod entity.
	// It exists in this package in order to avoid circular dependency with the "mod" package.
	ModInverseTable = "mods"
	// ModColumn is the table column denoting the mod relation/edge.
	ModColumn = "mod_paks"
)

// Columns holds all SQL columns for pak fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldInstalled,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "paks"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"mod_paks",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultInstalled holds the default value on creation for the "installed" field.
	DefaultInstalled bool
)

// OrderOption defines the ordering options for the Pak queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByInstalled orders the results by the installed field.
func ByInstalled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInstalled, opts...).ToFunc()
}

// ByModField orders the results by mod field.
func ByModField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newModStep(), sql.OrderByField(field, opts...))
	}
}
func newModStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ModInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ModTable, ModColumn),
	)
}
