// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Archive is the predicate function for archive builders.
type Archive func(*sql.Selector)

// Mod is the predicate function for mod builders.
type Mod func(*sql.Selector)

// Pak is the predicate function for pak builders.
type Pak func(*sql.Selector)
