version: '3'

vars:
  MODULE_BASE_PATH: "github.com/jbarzegar/ron-mod-manager" 
  RON_MM_CONFIG_DIR: "{{.HOME}}/.config/ron-mod-manager"
  LDFLAGS: "{{.MODULE_BASE_PATH}}/config.ConfPath={{.RON_MM_CONFIG_DIR}}"
  GO_OUTPUT: "./dist/ron-mod-manager"



tasks:
  build:  
    cmds:
      - go build -v -ldflags "-X "{{.LDFLAGS}}"" -o "{{.GO_OUTPUT}}" .
      
  install:
    description: "Install to bin location"
    vars: 
      BIN_LOCATION: "{{.HOME}}/.bin/ron-mm"
    cmds:
      - task: build
      - mkdir -p {{.BIN_LOCATION}}
      - mv {{.GO_OUTPUT}} {{.BIN_LOCATION}}/ron-mod-manager

  dev:
    vars:
      RON_MM_CONFIG_DIR: "./test/.conf"
      LDFLAGS: "{{.MODULE_BASE_PATH}}/config.ConfPath={{.RON_MM_CONFIG_DIR}}"
    cmds:
      - go run -ldflags "-X {{.LDFLAGS}}" . {{.CLI_ARGS}}

  ent:
    cmds:
      - go run -mod=mod entgo.io/ent/cmd/ent {{.CLI_ARGS}} 