version: "3"

tasks:
  install:
    cmds:
      - "echo $PWD && bun install"
  fmt:
    sources:
      - "./src/**/*"
    cmds:
      - "npx prettier -w src"
  dev:
    cmds:
      - "bun run tauri dev"
  storybook:
    cmds:
      - "bun run storybook"
