// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/jbarzegar/ron-mod-manager/ent/archive"
	"github.com/jbarzegar/ron-mod-manager/ent/predicate"
)

// ArchiveUpdate is the builder for updating Archive entities.
type ArchiveUpdate struct {
	config
	hooks    []Hook
	mutation *ArchiveMutation
}

// Where appends a list predicates to the ArchiveUpdate builder.
func (au *ArchiveUpdate) Where(ps ...predicate.Archive) *ArchiveUpdate {
	au.mutation.Where(ps...)
	return au
}

// SetName sets the "name" field.
func (au *ArchiveUpdate) SetName(s string) *ArchiveUpdate {
	au.mutation.SetName(s)
	return au
}

// SetNillableName sets the "name" field if the given value is not nil.
func (au *ArchiveUpdate) SetNillableName(s *string) *ArchiveUpdate {
	if s != nil {
		au.SetName(*s)
	}
	return au
}

// SetArchivePath sets the "archivePath" field.
func (au *ArchiveUpdate) SetArchivePath(s string) *ArchiveUpdate {
	au.mutation.SetArchivePath(s)
	return au
}

// SetNillableArchivePath sets the "archivePath" field if the given value is not nil.
func (au *ArchiveUpdate) SetNillableArchivePath(s *string) *ArchiveUpdate {
	if s != nil {
		au.SetArchivePath(*s)
	}
	return au
}

// SetMd5Sum sets the "md5Sum" field.
func (au *ArchiveUpdate) SetMd5Sum(s string) *ArchiveUpdate {
	au.mutation.SetMd5Sum(s)
	return au
}

// SetNillableMd5Sum sets the "md5Sum" field if the given value is not nil.
func (au *ArchiveUpdate) SetNillableMd5Sum(s *string) *ArchiveUpdate {
	if s != nil {
		au.SetMd5Sum(*s)
	}
	return au
}

// SetInstalled sets the "installed" field.
func (au *ArchiveUpdate) SetInstalled(b bool) *ArchiveUpdate {
	au.mutation.SetInstalled(b)
	return au
}

// SetNillableInstalled sets the "installed" field if the given value is not nil.
func (au *ArchiveUpdate) SetNillableInstalled(b *bool) *ArchiveUpdate {
	if b != nil {
		au.SetInstalled(*b)
	}
	return au
}

// Mutation returns the ArchiveMutation object of the builder.
func (au *ArchiveUpdate) Mutation() *ArchiveMutation {
	return au.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (au *ArchiveUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, au.sqlSave, au.mutation, au.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (au *ArchiveUpdate) SaveX(ctx context.Context) int {
	affected, err := au.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (au *ArchiveUpdate) Exec(ctx context.Context) error {
	_, err := au.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (au *ArchiveUpdate) ExecX(ctx context.Context) {
	if err := au.Exec(ctx); err != nil {
		panic(err)
	}
}

func (au *ArchiveUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(archive.Table, archive.Columns, sqlgraph.NewFieldSpec(archive.FieldID, field.TypeInt))
	if ps := au.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := au.mutation.Name(); ok {
		_spec.SetField(archive.FieldName, field.TypeString, value)
	}
	if value, ok := au.mutation.ArchivePath(); ok {
		_spec.SetField(archive.FieldArchivePath, field.TypeString, value)
	}
	if value, ok := au.mutation.Md5Sum(); ok {
		_spec.SetField(archive.FieldMd5Sum, field.TypeString, value)
	}
	if value, ok := au.mutation.Installed(); ok {
		_spec.SetField(archive.FieldInstalled, field.TypeBool, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, au.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{archive.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	au.mutation.done = true
	return n, nil
}

// ArchiveUpdateOne is the builder for updating a single Archive entity.
type ArchiveUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ArchiveMutation
}

// SetName sets the "name" field.
func (auo *ArchiveUpdateOne) SetName(s string) *ArchiveUpdateOne {
	auo.mutation.SetName(s)
	return auo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (auo *ArchiveUpdateOne) SetNillableName(s *string) *ArchiveUpdateOne {
	if s != nil {
		auo.SetName(*s)
	}
	return auo
}

// SetArchivePath sets the "archivePath" field.
func (auo *ArchiveUpdateOne) SetArchivePath(s string) *ArchiveUpdateOne {
	auo.mutation.SetArchivePath(s)
	return auo
}

// SetNillableArchivePath sets the "archivePath" field if the given value is not nil.
func (auo *ArchiveUpdateOne) SetNillableArchivePath(s *string) *ArchiveUpdateOne {
	if s != nil {
		auo.SetArchivePath(*s)
	}
	return auo
}

// SetMd5Sum sets the "md5Sum" field.
func (auo *ArchiveUpdateOne) SetMd5Sum(s string) *ArchiveUpdateOne {
	auo.mutation.SetMd5Sum(s)
	return auo
}

// SetNillableMd5Sum sets the "md5Sum" field if the given value is not nil.
func (auo *ArchiveUpdateOne) SetNillableMd5Sum(s *string) *ArchiveUpdateOne {
	if s != nil {
		auo.SetMd5Sum(*s)
	}
	return auo
}

// SetInstalled sets the "installed" field.
func (auo *ArchiveUpdateOne) SetInstalled(b bool) *ArchiveUpdateOne {
	auo.mutation.SetInstalled(b)
	return auo
}

// SetNillableInstalled sets the "installed" field if the given value is not nil.
func (auo *ArchiveUpdateOne) SetNillableInstalled(b *bool) *ArchiveUpdateOne {
	if b != nil {
		auo.SetInstalled(*b)
	}
	return auo
}

// Mutation returns the ArchiveMutation object of the builder.
func (auo *ArchiveUpdateOne) Mutation() *ArchiveMutation {
	return auo.mutation
}

// Where appends a list predicates to the ArchiveUpdate builder.
func (auo *ArchiveUpdateOne) Where(ps ...predicate.Archive) *ArchiveUpdateOne {
	auo.mutation.Where(ps...)
	return auo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (auo *ArchiveUpdateOne) Select(field string, fields ...string) *ArchiveUpdateOne {
	auo.fields = append([]string{field}, fields...)
	return auo
}

// Save executes the query and returns the updated Archive entity.
func (auo *ArchiveUpdateOne) Save(ctx context.Context) (*Archive, error) {
	return withHooks(ctx, auo.sqlSave, auo.mutation, auo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (auo *ArchiveUpdateOne) SaveX(ctx context.Context) *Archive {
	node, err := auo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (auo *ArchiveUpdateOne) Exec(ctx context.Context) error {
	_, err := auo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (auo *ArchiveUpdateOne) ExecX(ctx context.Context) {
	if err := auo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (auo *ArchiveUpdateOne) sqlSave(ctx context.Context) (_node *Archive, err error) {
	_spec := sqlgraph.NewUpdateSpec(archive.Table, archive.Columns, sqlgraph.NewFieldSpec(archive.FieldID, field.TypeInt))
	id, ok := auo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Archive.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := auo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, archive.FieldID)
		for _, f := range fields {
			if !archive.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != archive.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := auo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := auo.mutation.Name(); ok {
		_spec.SetField(archive.FieldName, field.TypeString, value)
	}
	if value, ok := auo.mutation.ArchivePath(); ok {
		_spec.SetField(archive.FieldArchivePath, field.TypeString, value)
	}
	if value, ok := auo.mutation.Md5Sum(); ok {
		_spec.SetField(archive.FieldMd5Sum, field.TypeString, value)
	}
	if value, ok := auo.mutation.Installed(); ok {
		_spec.SetField(archive.FieldInstalled, field.TypeBool, value)
	}
	_node = &Archive{config: auo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, auo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{archive.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	auo.mutation.done = true
	return _node, nil
}
