// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/jbarzegar/ron-mod-manager/ent/archive"
)

// ArchiveCreate is the builder for creating a Archive entity.
type ArchiveCreate struct {
	config
	mutation *ArchiveMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (ac *ArchiveCreate) SetName(s string) *ArchiveCreate {
	ac.mutation.SetName(s)
	return ac
}

// SetArchivePath sets the "archivePath" field.
func (ac *ArchiveCreate) SetArchivePath(s string) *ArchiveCreate {
	ac.mutation.SetArchivePath(s)
	return ac
}

// SetMd5Sum sets the "md5Sum" field.
func (ac *ArchiveCreate) SetMd5Sum(s string) *ArchiveCreate {
	ac.mutation.SetMd5Sum(s)
	return ac
}

// SetInstalled sets the "installed" field.
func (ac *ArchiveCreate) SetInstalled(b bool) *ArchiveCreate {
	ac.mutation.SetInstalled(b)
	return ac
}

// SetNillableInstalled sets the "installed" field if the given value is not nil.
func (ac *ArchiveCreate) SetNillableInstalled(b *bool) *ArchiveCreate {
	if b != nil {
		ac.SetInstalled(*b)
	}
	return ac
}

// Mutation returns the ArchiveMutation object of the builder.
func (ac *ArchiveCreate) Mutation() *ArchiveMutation {
	return ac.mutation
}

// Save creates the Archive in the database.
func (ac *ArchiveCreate) Save(ctx context.Context) (*Archive, error) {
	ac.defaults()
	return withHooks(ctx, ac.sqlSave, ac.mutation, ac.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ac *ArchiveCreate) SaveX(ctx context.Context) *Archive {
	v, err := ac.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ac *ArchiveCreate) Exec(ctx context.Context) error {
	_, err := ac.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ac *ArchiveCreate) ExecX(ctx context.Context) {
	if err := ac.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ac *ArchiveCreate) defaults() {
	if _, ok := ac.mutation.Installed(); !ok {
		v := archive.DefaultInstalled
		ac.mutation.SetInstalled(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ac *ArchiveCreate) check() error {
	if _, ok := ac.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Archive.name"`)}
	}
	if _, ok := ac.mutation.ArchivePath(); !ok {
		return &ValidationError{Name: "archivePath", err: errors.New(`ent: missing required field "Archive.archivePath"`)}
	}
	if _, ok := ac.mutation.Md5Sum(); !ok {
		return &ValidationError{Name: "md5Sum", err: errors.New(`ent: missing required field "Archive.md5Sum"`)}
	}
	if _, ok := ac.mutation.Installed(); !ok {
		return &ValidationError{Name: "installed", err: errors.New(`ent: missing required field "Archive.installed"`)}
	}
	return nil
}

func (ac *ArchiveCreate) sqlSave(ctx context.Context) (*Archive, error) {
	if err := ac.check(); err != nil {
		return nil, err
	}
	_node, _spec := ac.createSpec()
	if err := sqlgraph.CreateNode(ctx, ac.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	ac.mutation.id = &_node.ID
	ac.mutation.done = true
	return _node, nil
}

func (ac *ArchiveCreate) createSpec() (*Archive, *sqlgraph.CreateSpec) {
	var (
		_node = &Archive{config: ac.config}
		_spec = sqlgraph.NewCreateSpec(archive.Table, sqlgraph.NewFieldSpec(archive.FieldID, field.TypeInt))
	)
	if value, ok := ac.mutation.Name(); ok {
		_spec.SetField(archive.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := ac.mutation.ArchivePath(); ok {
		_spec.SetField(archive.FieldArchivePath, field.TypeString, value)
		_node.ArchivePath = value
	}
	if value, ok := ac.mutation.Md5Sum(); ok {
		_spec.SetField(archive.FieldMd5Sum, field.TypeString, value)
		_node.Md5Sum = value
	}
	if value, ok := ac.mutation.Installed(); ok {
		_spec.SetField(archive.FieldInstalled, field.TypeBool, value)
		_node.Installed = value
	}
	return _node, _spec
}

// ArchiveCreateBulk is the builder for creating many Archive entities in bulk.
type ArchiveCreateBulk struct {
	config
	err      error
	builders []*ArchiveCreate
}

// Save creates the Archive entities in the database.
func (acb *ArchiveCreateBulk) Save(ctx context.Context) ([]*Archive, error) {
	if acb.err != nil {
		return nil, acb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(acb.builders))
	nodes := make([]*Archive, len(acb.builders))
	mutators := make([]Mutator, len(acb.builders))
	for i := range acb.builders {
		func(i int, root context.Context) {
			builder := acb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ArchiveMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, acb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, acb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, acb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (acb *ArchiveCreateBulk) SaveX(ctx context.Context) []*Archive {
	v, err := acb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (acb *ArchiveCreateBulk) Exec(ctx context.Context) error {
	_, err := acb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (acb *ArchiveCreateBulk) ExecX(ctx context.Context) {
	if err := acb.Exec(ctx); err != nil {
		panic(err)
	}
}
