// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/jbarzegar/ron-mod-manager/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/jbarzegar/ron-mod-manager/ent/archive"
	"github.com/jbarzegar/ron-mod-manager/ent/mod"
	"github.com/jbarzegar/ron-mod-manager/ent/pak"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Archive is the client for interacting with the Archive builders.
	Archive *ArchiveClient
	// Mod is the client for interacting with the Mod builders.
	Mod *ModClient
	// Pak is the client for interacting with the Pak builders.
	Pak *PakClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Archive = NewArchiveClient(c.config)
	c.Mod = NewModClient(c.config)
	c.Pak = NewPakClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:     ctx,
		config:  cfg,
		Archive: NewArchiveClient(cfg),
		Mod:     NewModClient(cfg),
		Pak:     NewPakClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:     ctx,
		config:  cfg,
		Archive: NewArchiveClient(cfg),
		Mod:     NewModClient(cfg),
		Pak:     NewPakClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Archive.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Archive.Use(hooks...)
	c.Mod.Use(hooks...)
	c.Pak.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.Archive.Intercept(interceptors...)
	c.Mod.Intercept(interceptors...)
	c.Pak.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *ArchiveMutation:
		return c.Archive.mutate(ctx, m)
	case *ModMutation:
		return c.Mod.mutate(ctx, m)
	case *PakMutation:
		return c.Pak.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// ArchiveClient is a client for the Archive schema.
type ArchiveClient struct {
	config
}

// NewArchiveClient returns a client for the Archive from the given config.
func NewArchiveClient(c config) *ArchiveClient {
	return &ArchiveClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `archive.Hooks(f(g(h())))`.
func (c *ArchiveClient) Use(hooks ...Hook) {
	c.hooks.Archive = append(c.hooks.Archive, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `archive.Intercept(f(g(h())))`.
func (c *ArchiveClient) Intercept(interceptors ...Interceptor) {
	c.inters.Archive = append(c.inters.Archive, interceptors...)
}

// Create returns a builder for creating a Archive entity.
func (c *ArchiveClient) Create() *ArchiveCreate {
	mutation := newArchiveMutation(c.config, OpCreate)
	return &ArchiveCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Archive entities.
func (c *ArchiveClient) CreateBulk(builders ...*ArchiveCreate) *ArchiveCreateBulk {
	return &ArchiveCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ArchiveClient) MapCreateBulk(slice any, setFunc func(*ArchiveCreate, int)) *ArchiveCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ArchiveCreateBulk{err: fmt.Errorf("calling to ArchiveClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ArchiveCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ArchiveCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Archive.
func (c *ArchiveClient) Update() *ArchiveUpdate {
	mutation := newArchiveMutation(c.config, OpUpdate)
	return &ArchiveUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ArchiveClient) UpdateOne(a *Archive) *ArchiveUpdateOne {
	mutation := newArchiveMutation(c.config, OpUpdateOne, withArchive(a))
	return &ArchiveUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ArchiveClient) UpdateOneID(id int) *ArchiveUpdateOne {
	mutation := newArchiveMutation(c.config, OpUpdateOne, withArchiveID(id))
	return &ArchiveUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Archive.
func (c *ArchiveClient) Delete() *ArchiveDelete {
	mutation := newArchiveMutation(c.config, OpDelete)
	return &ArchiveDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ArchiveClient) DeleteOne(a *Archive) *ArchiveDeleteOne {
	return c.DeleteOneID(a.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ArchiveClient) DeleteOneID(id int) *ArchiveDeleteOne {
	builder := c.Delete().Where(archive.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ArchiveDeleteOne{builder}
}

// Query returns a query builder for Archive.
func (c *ArchiveClient) Query() *ArchiveQuery {
	return &ArchiveQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeArchive},
		inters: c.Interceptors(),
	}
}

// Get returns a Archive entity by its id.
func (c *ArchiveClient) Get(ctx context.Context, id int) (*Archive, error) {
	return c.Query().Where(archive.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ArchiveClient) GetX(ctx context.Context, id int) *Archive {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *ArchiveClient) Hooks() []Hook {
	return c.hooks.Archive
}

// Interceptors returns the client interceptors.
func (c *ArchiveClient) Interceptors() []Interceptor {
	return c.inters.Archive
}

func (c *ArchiveClient) mutate(ctx context.Context, m *ArchiveMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ArchiveCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ArchiveUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ArchiveUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ArchiveDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Archive mutation op: %q", m.Op())
	}
}

// ModClient is a client for the Mod schema.
type ModClient struct {
	config
}

// NewModClient returns a client for the Mod from the given config.
func NewModClient(c config) *ModClient {
	return &ModClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `mod.Hooks(f(g(h())))`.
func (c *ModClient) Use(hooks ...Hook) {
	c.hooks.Mod = append(c.hooks.Mod, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `mod.Intercept(f(g(h())))`.
func (c *ModClient) Intercept(interceptors ...Interceptor) {
	c.inters.Mod = append(c.inters.Mod, interceptors...)
}

// Create returns a builder for creating a Mod entity.
func (c *ModClient) Create() *ModCreate {
	mutation := newModMutation(c.config, OpCreate)
	return &ModCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Mod entities.
func (c *ModClient) CreateBulk(builders ...*ModCreate) *ModCreateBulk {
	return &ModCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ModClient) MapCreateBulk(slice any, setFunc func(*ModCreate, int)) *ModCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ModCreateBulk{err: fmt.Errorf("calling to ModClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ModCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ModCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Mod.
func (c *ModClient) Update() *ModUpdate {
	mutation := newModMutation(c.config, OpUpdate)
	return &ModUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ModClient) UpdateOne(m *Mod) *ModUpdateOne {
	mutation := newModMutation(c.config, OpUpdateOne, withMod(m))
	return &ModUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ModClient) UpdateOneID(id int) *ModUpdateOne {
	mutation := newModMutation(c.config, OpUpdateOne, withModID(id))
	return &ModUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Mod.
func (c *ModClient) Delete() *ModDelete {
	mutation := newModMutation(c.config, OpDelete)
	return &ModDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ModClient) DeleteOne(m *Mod) *ModDeleteOne {
	return c.DeleteOneID(m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ModClient) DeleteOneID(id int) *ModDeleteOne {
	builder := c.Delete().Where(mod.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ModDeleteOne{builder}
}

// Query returns a query builder for Mod.
func (c *ModClient) Query() *ModQuery {
	return &ModQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeMod},
		inters: c.Interceptors(),
	}
}

// Get returns a Mod entity by its id.
func (c *ModClient) Get(ctx context.Context, id int) (*Mod, error) {
	return c.Query().Where(mod.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ModClient) GetX(ctx context.Context, id int) *Mod {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryArchive queries the archive edge of a Mod.
func (c *ModClient) QueryArchive(m *Mod) *ArchiveQuery {
	query := (&ArchiveClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(mod.Table, mod.FieldID, id),
			sqlgraph.To(archive.Table, archive.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, mod.ArchiveTable, mod.ArchiveColumn),
		)
		fromV = sqlgraph.Neighbors(m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryPaks queries the paks edge of a Mod.
func (c *ModClient) QueryPaks(m *Mod) *PakQuery {
	query := (&PakClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(mod.Table, mod.FieldID, id),
			sqlgraph.To(pak.Table, pak.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, mod.PaksTable, mod.PaksColumn),
		)
		fromV = sqlgraph.Neighbors(m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ModClient) Hooks() []Hook {
	return c.hooks.Mod
}

// Interceptors returns the client interceptors.
func (c *ModClient) Interceptors() []Interceptor {
	return c.inters.Mod
}

func (c *ModClient) mutate(ctx context.Context, m *ModMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ModCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ModUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ModUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ModDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Mod mutation op: %q", m.Op())
	}
}

// PakClient is a client for the Pak schema.
type PakClient struct {
	config
}

// NewPakClient returns a client for the Pak from the given config.
func NewPakClient(c config) *PakClient {
	return &PakClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `pak.Hooks(f(g(h())))`.
func (c *PakClient) Use(hooks ...Hook) {
	c.hooks.Pak = append(c.hooks.Pak, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `pak.Intercept(f(g(h())))`.
func (c *PakClient) Intercept(interceptors ...Interceptor) {
	c.inters.Pak = append(c.inters.Pak, interceptors...)
}

// Create returns a builder for creating a Pak entity.
func (c *PakClient) Create() *PakCreate {
	mutation := newPakMutation(c.config, OpCreate)
	return &PakCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Pak entities.
func (c *PakClient) CreateBulk(builders ...*PakCreate) *PakCreateBulk {
	return &PakCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *PakClient) MapCreateBulk(slice any, setFunc func(*PakCreate, int)) *PakCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &PakCreateBulk{err: fmt.Errorf("calling to PakClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*PakCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &PakCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Pak.
func (c *PakClient) Update() *PakUpdate {
	mutation := newPakMutation(c.config, OpUpdate)
	return &PakUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *PakClient) UpdateOne(pa *Pak) *PakUpdateOne {
	mutation := newPakMutation(c.config, OpUpdateOne, withPak(pa))
	return &PakUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *PakClient) UpdateOneID(id int) *PakUpdateOne {
	mutation := newPakMutation(c.config, OpUpdateOne, withPakID(id))
	return &PakUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Pak.
func (c *PakClient) Delete() *PakDelete {
	mutation := newPakMutation(c.config, OpDelete)
	return &PakDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *PakClient) DeleteOne(pa *Pak) *PakDeleteOne {
	return c.DeleteOneID(pa.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *PakClient) DeleteOneID(id int) *PakDeleteOne {
	builder := c.Delete().Where(pak.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &PakDeleteOne{builder}
}

// Query returns a query builder for Pak.
func (c *PakClient) Query() *PakQuery {
	return &PakQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypePak},
		inters: c.Interceptors(),
	}
}

// Get returns a Pak entity by its id.
func (c *PakClient) Get(ctx context.Context, id int) (*Pak, error) {
	return c.Query().Where(pak.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *PakClient) GetX(ctx context.Context, id int) *Pak {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryMod queries the mod edge of a Pak.
func (c *PakClient) QueryMod(pa *Pak) *ModQuery {
	query := (&ModClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := pa.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(pak.Table, pak.FieldID, id),
			sqlgraph.To(mod.Table, mod.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, pak.ModTable, pak.ModColumn),
		)
		fromV = sqlgraph.Neighbors(pa.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *PakClient) Hooks() []Hook {
	return c.hooks.Pak
}

// Interceptors returns the client interceptors.
func (c *PakClient) Interceptors() []Interceptor {
	return c.inters.Pak
}

func (c *PakClient) mutate(ctx context.Context, m *PakMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&PakCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&PakUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&PakUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&PakDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Pak mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Archive, Mod, Pak []ent.Hook
	}
	inters struct {
		Archive, Mod, Pak []ent.Interceptor
	}
)
