// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/jbarzegar/ron-mod-manager/ent/archive"
	"github.com/jbarzegar/ron-mod-manager/ent/mod"
)

// Mod is the model entity for the Mod schema.
type Mod struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// State holds the value of the "state" field.
	State string `json:"state,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ModQuery when eager-loading is set.
	Edges        ModEdges `json:"edges"`
	mod_archive  *int
	selectValues sql.SelectValues
}

// ModEdges holds the relations/edges for other nodes in the graph.
type ModEdges struct {
	// Archive holds the value of the archive edge.
	Archive *Archive `json:"archive,omitempty"`
	// Paks holds the value of the paks edge.
	Paks []*Pak `json:"paks,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ArchiveOrErr returns the Archive value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ModEdges) ArchiveOrErr() (*Archive, error) {
	if e.loadedTypes[0] {
		if e.Archive == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: archive.Label}
		}
		return e.Archive, nil
	}
	return nil, &NotLoadedError{edge: "archive"}
}

// PaksOrErr returns the Paks value or an error if the edge
// was not loaded in eager-loading.
func (e ModEdges) PaksOrErr() ([]*Pak, error) {
	if e.loadedTypes[1] {
		return e.Paks, nil
	}
	return nil, &NotLoadedError{edge: "paks"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Mod) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case mod.FieldID:
			values[i] = new(sql.NullInt64)
		case mod.FieldName, mod.FieldState:
			values[i] = new(sql.NullString)
		case mod.ForeignKeys[0]: // mod_archive
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Mod fields.
func (m *Mod) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case mod.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			m.ID = int(value.Int64)
		case mod.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				m.Name = value.String
			}
		case mod.FieldState:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field state", values[i])
			} else if value.Valid {
				m.State = value.String
			}
		case mod.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field mod_archive", value)
			} else if value.Valid {
				m.mod_archive = new(int)
				*m.mod_archive = int(value.Int64)
			}
		default:
			m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Mod.
// This includes values selected through modifiers, order, etc.
func (m *Mod) Value(name string) (ent.Value, error) {
	return m.selectValues.Get(name)
}

// QueryArchive queries the "archive" edge of the Mod entity.
func (m *Mod) QueryArchive() *ArchiveQuery {
	return NewModClient(m.config).QueryArchive(m)
}

// QueryPaks queries the "paks" edge of the Mod entity.
func (m *Mod) QueryPaks() *PakQuery {
	return NewModClient(m.config).QueryPaks(m)
}

// Update returns a builder for updating this Mod.
// Note that you need to call Mod.Unwrap() before calling this method if this Mod
// was returned from a transaction, and the transaction was committed or rolled back.
func (m *Mod) Update() *ModUpdateOne {
	return NewModClient(m.config).UpdateOne(m)
}

// Unwrap unwraps the Mod entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (m *Mod) Unwrap() *Mod {
	_tx, ok := m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Mod is not a transactional entity")
	}
	m.config.driver = _tx.drv
	return m
}

// String implements the fmt.Stringer.
func (m *Mod) String() string {
	var builder strings.Builder
	builder.WriteString("Mod(")
	builder.WriteString(fmt.Sprintf("id=%v, ", m.ID))
	builder.WriteString("name=")
	builder.WriteString(m.Name)
	builder.WriteString(", ")
	builder.WriteString("state=")
	builder.WriteString(m.State)
	builder.WriteByte(')')
	return builder.String()
}

// Mods is a parsable slice of Mod.
type Mods []*Mod
