// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/jbarzegar/ron-mod-manager/ent/archive"
	"github.com/jbarzegar/ron-mod-manager/ent/mod"
	"github.com/jbarzegar/ron-mod-manager/ent/pak"
	"github.com/jbarzegar/ron-mod-manager/ent/predicate"
)

// ModUpdate is the builder for updating Mod entities.
type ModUpdate struct {
	config
	hooks    []Hook
	mutation *ModMutation
}

// Where appends a list predicates to the ModUpdate builder.
func (mu *ModUpdate) Where(ps ...predicate.Mod) *ModUpdate {
	mu.mutation.Where(ps...)
	return mu
}

// SetName sets the "name" field.
func (mu *ModUpdate) SetName(s string) *ModUpdate {
	mu.mutation.SetName(s)
	return mu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (mu *ModUpdate) SetNillableName(s *string) *ModUpdate {
	if s != nil {
		mu.SetName(*s)
	}
	return mu
}

// SetState sets the "state" field.
func (mu *ModUpdate) SetState(s string) *ModUpdate {
	mu.mutation.SetState(s)
	return mu
}

// SetNillableState sets the "state" field if the given value is not nil.
func (mu *ModUpdate) SetNillableState(s *string) *ModUpdate {
	if s != nil {
		mu.SetState(*s)
	}
	return mu
}

// SetArchiveID sets the "archive" edge to the Archive entity by ID.
func (mu *ModUpdate) SetArchiveID(id int) *ModUpdate {
	mu.mutation.SetArchiveID(id)
	return mu
}

// SetArchive sets the "archive" edge to the Archive entity.
func (mu *ModUpdate) SetArchive(a *Archive) *ModUpdate {
	return mu.SetArchiveID(a.ID)
}

// AddPakIDs adds the "paks" edge to the Pak entity by IDs.
func (mu *ModUpdate) AddPakIDs(ids ...int) *ModUpdate {
	mu.mutation.AddPakIDs(ids...)
	return mu
}

// AddPaks adds the "paks" edges to the Pak entity.
func (mu *ModUpdate) AddPaks(p ...*Pak) *ModUpdate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return mu.AddPakIDs(ids...)
}

// Mutation returns the ModMutation object of the builder.
func (mu *ModUpdate) Mutation() *ModMutation {
	return mu.mutation
}

// ClearArchive clears the "archive" edge to the Archive entity.
func (mu *ModUpdate) ClearArchive() *ModUpdate {
	mu.mutation.ClearArchive()
	return mu
}

// ClearPaks clears all "paks" edges to the Pak entity.
func (mu *ModUpdate) ClearPaks() *ModUpdate {
	mu.mutation.ClearPaks()
	return mu
}

// RemovePakIDs removes the "paks" edge to Pak entities by IDs.
func (mu *ModUpdate) RemovePakIDs(ids ...int) *ModUpdate {
	mu.mutation.RemovePakIDs(ids...)
	return mu
}

// RemovePaks removes "paks" edges to Pak entities.
func (mu *ModUpdate) RemovePaks(p ...*Pak) *ModUpdate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return mu.RemovePakIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (mu *ModUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, mu.sqlSave, mu.mutation, mu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (mu *ModUpdate) SaveX(ctx context.Context) int {
	affected, err := mu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (mu *ModUpdate) Exec(ctx context.Context) error {
	_, err := mu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mu *ModUpdate) ExecX(ctx context.Context) {
	if err := mu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mu *ModUpdate) check() error {
	if v, ok := mu.mutation.State(); ok {
		if err := mod.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "Mod.state": %w`, err)}
		}
	}
	if _, ok := mu.mutation.ArchiveID(); mu.mutation.ArchiveCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Mod.archive"`)
	}
	return nil
}

func (mu *ModUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := mu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(mod.Table, mod.Columns, sqlgraph.NewFieldSpec(mod.FieldID, field.TypeInt))
	if ps := mu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := mu.mutation.Name(); ok {
		_spec.SetField(mod.FieldName, field.TypeString, value)
	}
	if value, ok := mu.mutation.State(); ok {
		_spec.SetField(mod.FieldState, field.TypeString, value)
	}
	if mu.mutation.ArchiveCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   mod.ArchiveTable,
			Columns: []string{mod.ArchiveColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(archive.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mu.mutation.ArchiveIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   mod.ArchiveTable,
			Columns: []string{mod.ArchiveColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(archive.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if mu.mutation.PaksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   mod.PaksTable,
			Columns: []string{mod.PaksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pak.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mu.mutation.RemovedPaksIDs(); len(nodes) > 0 && !mu.mutation.PaksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   mod.PaksTable,
			Columns: []string{mod.PaksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pak.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mu.mutation.PaksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   mod.PaksTable,
			Columns: []string{mod.PaksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pak.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, mu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mod.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	mu.mutation.done = true
	return n, nil
}

// ModUpdateOne is the builder for updating a single Mod entity.
type ModUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ModMutation
}

// SetName sets the "name" field.
func (muo *ModUpdateOne) SetName(s string) *ModUpdateOne {
	muo.mutation.SetName(s)
	return muo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (muo *ModUpdateOne) SetNillableName(s *string) *ModUpdateOne {
	if s != nil {
		muo.SetName(*s)
	}
	return muo
}

// SetState sets the "state" field.
func (muo *ModUpdateOne) SetState(s string) *ModUpdateOne {
	muo.mutation.SetState(s)
	return muo
}

// SetNillableState sets the "state" field if the given value is not nil.
func (muo *ModUpdateOne) SetNillableState(s *string) *ModUpdateOne {
	if s != nil {
		muo.SetState(*s)
	}
	return muo
}

// SetArchiveID sets the "archive" edge to the Archive entity by ID.
func (muo *ModUpdateOne) SetArchiveID(id int) *ModUpdateOne {
	muo.mutation.SetArchiveID(id)
	return muo
}

// SetArchive sets the "archive" edge to the Archive entity.
func (muo *ModUpdateOne) SetArchive(a *Archive) *ModUpdateOne {
	return muo.SetArchiveID(a.ID)
}

// AddPakIDs adds the "paks" edge to the Pak entity by IDs.
func (muo *ModUpdateOne) AddPakIDs(ids ...int) *ModUpdateOne {
	muo.mutation.AddPakIDs(ids...)
	return muo
}

// AddPaks adds the "paks" edges to the Pak entity.
func (muo *ModUpdateOne) AddPaks(p ...*Pak) *ModUpdateOne {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return muo.AddPakIDs(ids...)
}

// Mutation returns the ModMutation object of the builder.
func (muo *ModUpdateOne) Mutation() *ModMutation {
	return muo.mutation
}

// ClearArchive clears the "archive" edge to the Archive entity.
func (muo *ModUpdateOne) ClearArchive() *ModUpdateOne {
	muo.mutation.ClearArchive()
	return muo
}

// ClearPaks clears all "paks" edges to the Pak entity.
func (muo *ModUpdateOne) ClearPaks() *ModUpdateOne {
	muo.mutation.ClearPaks()
	return muo
}

// RemovePakIDs removes the "paks" edge to Pak entities by IDs.
func (muo *ModUpdateOne) RemovePakIDs(ids ...int) *ModUpdateOne {
	muo.mutation.RemovePakIDs(ids...)
	return muo
}

// RemovePaks removes "paks" edges to Pak entities.
func (muo *ModUpdateOne) RemovePaks(p ...*Pak) *ModUpdateOne {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return muo.RemovePakIDs(ids...)
}

// Where appends a list predicates to the ModUpdate builder.
func (muo *ModUpdateOne) Where(ps ...predicate.Mod) *ModUpdateOne {
	muo.mutation.Where(ps...)
	return muo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (muo *ModUpdateOne) Select(field string, fields ...string) *ModUpdateOne {
	muo.fields = append([]string{field}, fields...)
	return muo
}

// Save executes the query and returns the updated Mod entity.
func (muo *ModUpdateOne) Save(ctx context.Context) (*Mod, error) {
	return withHooks(ctx, muo.sqlSave, muo.mutation, muo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (muo *ModUpdateOne) SaveX(ctx context.Context) *Mod {
	node, err := muo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (muo *ModUpdateOne) Exec(ctx context.Context) error {
	_, err := muo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (muo *ModUpdateOne) ExecX(ctx context.Context) {
	if err := muo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (muo *ModUpdateOne) check() error {
	if v, ok := muo.mutation.State(); ok {
		if err := mod.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "Mod.state": %w`, err)}
		}
	}
	if _, ok := muo.mutation.ArchiveID(); muo.mutation.ArchiveCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Mod.archive"`)
	}
	return nil
}

func (muo *ModUpdateOne) sqlSave(ctx context.Context) (_node *Mod, err error) {
	if err := muo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(mod.Table, mod.Columns, sqlgraph.NewFieldSpec(mod.FieldID, field.TypeInt))
	id, ok := muo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Mod.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := muo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, mod.FieldID)
		for _, f := range fields {
			if !mod.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != mod.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := muo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := muo.mutation.Name(); ok {
		_spec.SetField(mod.FieldName, field.TypeString, value)
	}
	if value, ok := muo.mutation.State(); ok {
		_spec.SetField(mod.FieldState, field.TypeString, value)
	}
	if muo.mutation.ArchiveCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   mod.ArchiveTable,
			Columns: []string{mod.ArchiveColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(archive.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := muo.mutation.ArchiveIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   mod.ArchiveTable,
			Columns: []string{mod.ArchiveColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(archive.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if muo.mutation.PaksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   mod.PaksTable,
			Columns: []string{mod.PaksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pak.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := muo.mutation.RemovedPaksIDs(); len(nodes) > 0 && !muo.mutation.PaksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   mod.PaksTable,
			Columns: []string{mod.PaksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pak.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := muo.mutation.PaksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   mod.PaksTable,
			Columns: []string{mod.PaksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pak.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Mod{config: muo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, muo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mod.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	muo.mutation.done = true
	return _node, nil
}
