// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/jbarzegar/ron-mod-manager/ent/archive"
	"github.com/jbarzegar/ron-mod-manager/ent/mod"
	"github.com/jbarzegar/ron-mod-manager/ent/pak"
)

// ModCreate is the builder for creating a Mod entity.
type ModCreate struct {
	config
	mutation *ModMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (mc *ModCreate) SetName(s string) *ModCreate {
	mc.mutation.SetName(s)
	return mc
}

// SetState sets the "state" field.
func (mc *ModCreate) SetState(s string) *ModCreate {
	mc.mutation.SetState(s)
	return mc
}

// SetArchiveID sets the "archive" edge to the Archive entity by ID.
func (mc *ModCreate) SetArchiveID(id int) *ModCreate {
	mc.mutation.SetArchiveID(id)
	return mc
}

// SetArchive sets the "archive" edge to the Archive entity.
func (mc *ModCreate) SetArchive(a *Archive) *ModCreate {
	return mc.SetArchiveID(a.ID)
}

// AddPakIDs adds the "paks" edge to the Pak entity by IDs.
func (mc *ModCreate) AddPakIDs(ids ...int) *ModCreate {
	mc.mutation.AddPakIDs(ids...)
	return mc
}

// AddPaks adds the "paks" edges to the Pak entity.
func (mc *ModCreate) AddPaks(p ...*Pak) *ModCreate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return mc.AddPakIDs(ids...)
}

// Mutation returns the ModMutation object of the builder.
func (mc *ModCreate) Mutation() *ModMutation {
	return mc.mutation
}

// Save creates the Mod in the database.
func (mc *ModCreate) Save(ctx context.Context) (*Mod, error) {
	return withHooks(ctx, mc.sqlSave, mc.mutation, mc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (mc *ModCreate) SaveX(ctx context.Context) *Mod {
	v, err := mc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mc *ModCreate) Exec(ctx context.Context) error {
	_, err := mc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mc *ModCreate) ExecX(ctx context.Context) {
	if err := mc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mc *ModCreate) check() error {
	if _, ok := mc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Mod.name"`)}
	}
	if _, ok := mc.mutation.State(); !ok {
		return &ValidationError{Name: "state", err: errors.New(`ent: missing required field "Mod.state"`)}
	}
	if v, ok := mc.mutation.State(); ok {
		if err := mod.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "Mod.state": %w`, err)}
		}
	}
	if _, ok := mc.mutation.ArchiveID(); !ok {
		return &ValidationError{Name: "archive", err: errors.New(`ent: missing required edge "Mod.archive"`)}
	}
	return nil
}

func (mc *ModCreate) sqlSave(ctx context.Context) (*Mod, error) {
	if err := mc.check(); err != nil {
		return nil, err
	}
	_node, _spec := mc.createSpec()
	if err := sqlgraph.CreateNode(ctx, mc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	mc.mutation.id = &_node.ID
	mc.mutation.done = true
	return _node, nil
}

func (mc *ModCreate) createSpec() (*Mod, *sqlgraph.CreateSpec) {
	var (
		_node = &Mod{config: mc.config}
		_spec = sqlgraph.NewCreateSpec(mod.Table, sqlgraph.NewFieldSpec(mod.FieldID, field.TypeInt))
	)
	if value, ok := mc.mutation.Name(); ok {
		_spec.SetField(mod.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := mc.mutation.State(); ok {
		_spec.SetField(mod.FieldState, field.TypeString, value)
		_node.State = value
	}
	if nodes := mc.mutation.ArchiveIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   mod.ArchiveTable,
			Columns: []string{mod.ArchiveColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(archive.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.mod_archive = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := mc.mutation.PaksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   mod.PaksTable,
			Columns: []string{mod.PaksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pak.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ModCreateBulk is the builder for creating many Mod entities in bulk.
type ModCreateBulk struct {
	config
	err      error
	builders []*ModCreate
}

// Save creates the Mod entities in the database.
func (mcb *ModCreateBulk) Save(ctx context.Context) ([]*Mod, error) {
	if mcb.err != nil {
		return nil, mcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(mcb.builders))
	nodes := make([]*Mod, len(mcb.builders))
	mutators := make([]Mutator, len(mcb.builders))
	for i := range mcb.builders {
		func(i int, root context.Context) {
			builder := mcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ModMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, mcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, mcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, mcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (mcb *ModCreateBulk) SaveX(ctx context.Context) []*Mod {
	v, err := mcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mcb *ModCreateBulk) Exec(ctx context.Context) error {
	_, err := mcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mcb *ModCreateBulk) ExecX(ctx context.Context) {
	if err := mcb.Exec(ctx); err != nil {
		panic(err)
	}
}
