// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/jbarzegar/ron-mod-manager/ent/archive"
	"github.com/jbarzegar/ron-mod-manager/ent/mod"
	"github.com/jbarzegar/ron-mod-manager/ent/pak"
	"github.com/jbarzegar/ron-mod-manager/ent/predicate"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeArchive = "Archive"
	TypeMod     = "Mod"
	TypePak     = "Pak"
)

// ArchiveMutation represents an operation that mutates the Archive nodes in the graph.
type ArchiveMutation struct {
	config
	op            Op
	typ           string
	id            *int
	name          *string
	archivePath   *string
	md5Sum        *string
	installed     *bool
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*Archive, error)
	predicates    []predicate.Archive
}

var _ ent.Mutation = (*ArchiveMutation)(nil)

// archiveOption allows management of the mutation configuration using functional options.
type archiveOption func(*ArchiveMutation)

// newArchiveMutation creates new mutation for the Archive entity.
func newArchiveMutation(c config, op Op, opts ...archiveOption) *ArchiveMutation {
	m := &ArchiveMutation{
		config:        c,
		op:            op,
		typ:           TypeArchive,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withArchiveID sets the ID field of the mutation.
func withArchiveID(id int) archiveOption {
	return func(m *ArchiveMutation) {
		var (
			err   error
			once  sync.Once
			value *Archive
		)
		m.oldValue = func(ctx context.Context) (*Archive, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Archive.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withArchive sets the old Archive of the mutation.
func withArchive(node *Archive) archiveOption {
	return func(m *ArchiveMutation) {
		m.oldValue = func(context.Context) (*Archive, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m ArchiveMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m ArchiveMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *ArchiveMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *ArchiveMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Archive.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetName sets the "name" field.
func (m *ArchiveMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *ArchiveMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the Archive entity.
// If the Archive object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ArchiveMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *ArchiveMutation) ResetName() {
	m.name = nil
}

// SetArchivePath sets the "archivePath" field.
func (m *ArchiveMutation) SetArchivePath(s string) {
	m.archivePath = &s
}

// ArchivePath returns the value of the "archivePath" field in the mutation.
func (m *ArchiveMutation) ArchivePath() (r string, exists bool) {
	v := m.archivePath
	if v == nil {
		return
	}
	return *v, true
}

// OldArchivePath returns the old "archivePath" field's value of the Archive entity.
// If the Archive object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ArchiveMutation) OldArchivePath(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldArchivePath is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldArchivePath requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldArchivePath: %w", err)
	}
	return oldValue.ArchivePath, nil
}

// ResetArchivePath resets all changes to the "archivePath" field.
func (m *ArchiveMutation) ResetArchivePath() {
	m.archivePath = nil
}

// SetMd5Sum sets the "md5Sum" field.
func (m *ArchiveMutation) SetMd5Sum(s string) {
	m.md5Sum = &s
}

// Md5Sum returns the value of the "md5Sum" field in the mutation.
func (m *ArchiveMutation) Md5Sum() (r string, exists bool) {
	v := m.md5Sum
	if v == nil {
		return
	}
	return *v, true
}

// OldMd5Sum returns the old "md5Sum" field's value of the Archive entity.
// If the Archive object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ArchiveMutation) OldMd5Sum(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldMd5Sum is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldMd5Sum requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldMd5Sum: %w", err)
	}
	return oldValue.Md5Sum, nil
}

// ResetMd5Sum resets all changes to the "md5Sum" field.
func (m *ArchiveMutation) ResetMd5Sum() {
	m.md5Sum = nil
}

// SetInstalled sets the "installed" field.
func (m *ArchiveMutation) SetInstalled(b bool) {
	m.installed = &b
}

// Installed returns the value of the "installed" field in the mutation.
func (m *ArchiveMutation) Installed() (r bool, exists bool) {
	v := m.installed
	if v == nil {
		return
	}
	return *v, true
}

// OldInstalled returns the old "installed" field's value of the Archive entity.
// If the Archive object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ArchiveMutation) OldInstalled(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldInstalled is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldInstalled requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldInstalled: %w", err)
	}
	return oldValue.Installed, nil
}

// ResetInstalled resets all changes to the "installed" field.
func (m *ArchiveMutation) ResetInstalled() {
	m.installed = nil
}

// Where appends a list predicates to the ArchiveMutation builder.
func (m *ArchiveMutation) Where(ps ...predicate.Archive) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the ArchiveMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *ArchiveMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Archive, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *ArchiveMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *ArchiveMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Archive).
func (m *ArchiveMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *ArchiveMutation) Fields() []string {
	fields := make([]string, 0, 4)
	if m.name != nil {
		fields = append(fields, archive.FieldName)
	}
	if m.archivePath != nil {
		fields = append(fields, archive.FieldArchivePath)
	}
	if m.md5Sum != nil {
		fields = append(fields, archive.FieldMd5Sum)
	}
	if m.installed != nil {
		fields = append(fields, archive.FieldInstalled)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *ArchiveMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case archive.FieldName:
		return m.Name()
	case archive.FieldArchivePath:
		return m.ArchivePath()
	case archive.FieldMd5Sum:
		return m.Md5Sum()
	case archive.FieldInstalled:
		return m.Installed()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *ArchiveMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case archive.FieldName:
		return m.OldName(ctx)
	case archive.FieldArchivePath:
		return m.OldArchivePath(ctx)
	case archive.FieldMd5Sum:
		return m.OldMd5Sum(ctx)
	case archive.FieldInstalled:
		return m.OldInstalled(ctx)
	}
	return nil, fmt.Errorf("unknown Archive field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ArchiveMutation) SetField(name string, value ent.Value) error {
	switch name {
	case archive.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case archive.FieldArchivePath:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetArchivePath(v)
		return nil
	case archive.FieldMd5Sum:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetMd5Sum(v)
		return nil
	case archive.FieldInstalled:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetInstalled(v)
		return nil
	}
	return fmt.Errorf("unknown Archive field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *ArchiveMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *ArchiveMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ArchiveMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Archive numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *ArchiveMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *ArchiveMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *ArchiveMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Archive nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *ArchiveMutation) ResetField(name string) error {
	switch name {
	case archive.FieldName:
		m.ResetName()
		return nil
	case archive.FieldArchivePath:
		m.ResetArchivePath()
		return nil
	case archive.FieldMd5Sum:
		m.ResetMd5Sum()
		return nil
	case archive.FieldInstalled:
		m.ResetInstalled()
		return nil
	}
	return fmt.Errorf("unknown Archive field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *ArchiveMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *ArchiveMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *ArchiveMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *ArchiveMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *ArchiveMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *ArchiveMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *ArchiveMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Archive unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *ArchiveMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Archive edge %s", name)
}

// ModMutation represents an operation that mutates the Mod nodes in the graph.
type ModMutation struct {
	config
	op             Op
	typ            string
	id             *int
	name           *string
	state          *string
	clearedFields  map[string]struct{}
	archive        *int
	clearedarchive bool
	paks           map[int]struct{}
	removedpaks    map[int]struct{}
	clearedpaks    bool
	done           bool
	oldValue       func(context.Context) (*Mod, error)
	predicates     []predicate.Mod
}

var _ ent.Mutation = (*ModMutation)(nil)

// modOption allows management of the mutation configuration using functional options.
type modOption func(*ModMutation)

// newModMutation creates new mutation for the Mod entity.
func newModMutation(c config, op Op, opts ...modOption) *ModMutation {
	m := &ModMutation{
		config:        c,
		op:            op,
		typ:           TypeMod,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withModID sets the ID field of the mutation.
func withModID(id int) modOption {
	return func(m *ModMutation) {
		var (
			err   error
			once  sync.Once
			value *Mod
		)
		m.oldValue = func(ctx context.Context) (*Mod, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Mod.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withMod sets the old Mod of the mutation.
func withMod(node *Mod) modOption {
	return func(m *ModMutation) {
		m.oldValue = func(context.Context) (*Mod, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m ModMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m ModMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *ModMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *ModMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Mod.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetName sets the "name" field.
func (m *ModMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *ModMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the Mod entity.
// If the Mod object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ModMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *ModMutation) ResetName() {
	m.name = nil
}

// SetState sets the "state" field.
func (m *ModMutation) SetState(s string) {
	m.state = &s
}

// State returns the value of the "state" field in the mutation.
func (m *ModMutation) State() (r string, exists bool) {
	v := m.state
	if v == nil {
		return
	}
	return *v, true
}

// OldState returns the old "state" field's value of the Mod entity.
// If the Mod object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ModMutation) OldState(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldState is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldState requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldState: %w", err)
	}
	return oldValue.State, nil
}

// ResetState resets all changes to the "state" field.
func (m *ModMutation) ResetState() {
	m.state = nil
}

// SetArchiveID sets the "archive" edge to the Archive entity by id.
func (m *ModMutation) SetArchiveID(id int) {
	m.archive = &id
}

// ClearArchive clears the "archive" edge to the Archive entity.
func (m *ModMutation) ClearArchive() {
	m.clearedarchive = true
}

// ArchiveCleared reports if the "archive" edge to the Archive entity was cleared.
func (m *ModMutation) ArchiveCleared() bool {
	return m.clearedarchive
}

// ArchiveID returns the "archive" edge ID in the mutation.
func (m *ModMutation) ArchiveID() (id int, exists bool) {
	if m.archive != nil {
		return *m.archive, true
	}
	return
}

// ArchiveIDs returns the "archive" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// ArchiveID instead. It exists only for internal usage by the builders.
func (m *ModMutation) ArchiveIDs() (ids []int) {
	if id := m.archive; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetArchive resets all changes to the "archive" edge.
func (m *ModMutation) ResetArchive() {
	m.archive = nil
	m.clearedarchive = false
}

// AddPakIDs adds the "paks" edge to the Pak entity by ids.
func (m *ModMutation) AddPakIDs(ids ...int) {
	if m.paks == nil {
		m.paks = make(map[int]struct{})
	}
	for i := range ids {
		m.paks[ids[i]] = struct{}{}
	}
}

// ClearPaks clears the "paks" edge to the Pak entity.
func (m *ModMutation) ClearPaks() {
	m.clearedpaks = true
}

// PaksCleared reports if the "paks" edge to the Pak entity was cleared.
func (m *ModMutation) PaksCleared() bool {
	return m.clearedpaks
}

// RemovePakIDs removes the "paks" edge to the Pak entity by IDs.
func (m *ModMutation) RemovePakIDs(ids ...int) {
	if m.removedpaks == nil {
		m.removedpaks = make(map[int]struct{})
	}
	for i := range ids {
		delete(m.paks, ids[i])
		m.removedpaks[ids[i]] = struct{}{}
	}
}

// RemovedPaks returns the removed IDs of the "paks" edge to the Pak entity.
func (m *ModMutation) RemovedPaksIDs() (ids []int) {
	for id := range m.removedpaks {
		ids = append(ids, id)
	}
	return
}

// PaksIDs returns the "paks" edge IDs in the mutation.
func (m *ModMutation) PaksIDs() (ids []int) {
	for id := range m.paks {
		ids = append(ids, id)
	}
	return
}

// ResetPaks resets all changes to the "paks" edge.
func (m *ModMutation) ResetPaks() {
	m.paks = nil
	m.clearedpaks = false
	m.removedpaks = nil
}

// Where appends a list predicates to the ModMutation builder.
func (m *ModMutation) Where(ps ...predicate.Mod) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the ModMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *ModMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Mod, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *ModMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *ModMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Mod).
func (m *ModMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *ModMutation) Fields() []string {
	fields := make([]string, 0, 2)
	if m.name != nil {
		fields = append(fields, mod.FieldName)
	}
	if m.state != nil {
		fields = append(fields, mod.FieldState)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *ModMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case mod.FieldName:
		return m.Name()
	case mod.FieldState:
		return m.State()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *ModMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case mod.FieldName:
		return m.OldName(ctx)
	case mod.FieldState:
		return m.OldState(ctx)
	}
	return nil, fmt.Errorf("unknown Mod field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ModMutation) SetField(name string, value ent.Value) error {
	switch name {
	case mod.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case mod.FieldState:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetState(v)
		return nil
	}
	return fmt.Errorf("unknown Mod field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *ModMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *ModMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ModMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Mod numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *ModMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *ModMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *ModMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Mod nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *ModMutation) ResetField(name string) error {
	switch name {
	case mod.FieldName:
		m.ResetName()
		return nil
	case mod.FieldState:
		m.ResetState()
		return nil
	}
	return fmt.Errorf("unknown Mod field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *ModMutation) AddedEdges() []string {
	edges := make([]string, 0, 2)
	if m.archive != nil {
		edges = append(edges, mod.EdgeArchive)
	}
	if m.paks != nil {
		edges = append(edges, mod.EdgePaks)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *ModMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case mod.EdgeArchive:
		if id := m.archive; id != nil {
			return []ent.Value{*id}
		}
	case mod.EdgePaks:
		ids := make([]ent.Value, 0, len(m.paks))
		for id := range m.paks {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *ModMutation) RemovedEdges() []string {
	edges := make([]string, 0, 2)
	if m.removedpaks != nil {
		edges = append(edges, mod.EdgePaks)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *ModMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case mod.EdgePaks:
		ids := make([]ent.Value, 0, len(m.removedpaks))
		for id := range m.removedpaks {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *ModMutation) ClearedEdges() []string {
	edges := make([]string, 0, 2)
	if m.clearedarchive {
		edges = append(edges, mod.EdgeArchive)
	}
	if m.clearedpaks {
		edges = append(edges, mod.EdgePaks)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *ModMutation) EdgeCleared(name string) bool {
	switch name {
	case mod.EdgeArchive:
		return m.clearedarchive
	case mod.EdgePaks:
		return m.clearedpaks
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *ModMutation) ClearEdge(name string) error {
	switch name {
	case mod.EdgeArchive:
		m.ClearArchive()
		return nil
	}
	return fmt.Errorf("unknown Mod unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *ModMutation) ResetEdge(name string) error {
	switch name {
	case mod.EdgeArchive:
		m.ResetArchive()
		return nil
	case mod.EdgePaks:
		m.ResetPaks()
		return nil
	}
	return fmt.Errorf("unknown Mod edge %s", name)
}

// PakMutation represents an operation that mutates the Pak nodes in the graph.
type PakMutation struct {
	config
	op            Op
	typ           string
	id            *int
	name          *string
	installed     *bool
	clearedFields map[string]struct{}
	mod           *int
	clearedmod    bool
	done          bool
	oldValue      func(context.Context) (*Pak, error)
	predicates    []predicate.Pak
}

var _ ent.Mutation = (*PakMutation)(nil)

// pakOption allows management of the mutation configuration using functional options.
type pakOption func(*PakMutation)

// newPakMutation creates new mutation for the Pak entity.
func newPakMutation(c config, op Op, opts ...pakOption) *PakMutation {
	m := &PakMutation{
		config:        c,
		op:            op,
		typ:           TypePak,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withPakID sets the ID field of the mutation.
func withPakID(id int) pakOption {
	return func(m *PakMutation) {
		var (
			err   error
			once  sync.Once
			value *Pak
		)
		m.oldValue = func(ctx context.Context) (*Pak, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Pak.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withPak sets the old Pak of the mutation.
func withPak(node *Pak) pakOption {
	return func(m *PakMutation) {
		m.oldValue = func(context.Context) (*Pak, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m PakMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m PakMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *PakMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *PakMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Pak.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetName sets the "name" field.
func (m *PakMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *PakMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the Pak entity.
// If the Pak object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PakMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *PakMutation) ResetName() {
	m.name = nil
}

// SetInstalled sets the "installed" field.
func (m *PakMutation) SetInstalled(b bool) {
	m.installed = &b
}

// Installed returns the value of the "installed" field in the mutation.
func (m *PakMutation) Installed() (r bool, exists bool) {
	v := m.installed
	if v == nil {
		return
	}
	return *v, true
}

// OldInstalled returns the old "installed" field's value of the Pak entity.
// If the Pak object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PakMutation) OldInstalled(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldInstalled is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldInstalled requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldInstalled: %w", err)
	}
	return oldValue.Installed, nil
}

// ResetInstalled resets all changes to the "installed" field.
func (m *PakMutation) ResetInstalled() {
	m.installed = nil
}

// SetModID sets the "mod" edge to the Mod entity by id.
func (m *PakMutation) SetModID(id int) {
	m.mod = &id
}

// ClearMod clears the "mod" edge to the Mod entity.
func (m *PakMutation) ClearMod() {
	m.clearedmod = true
}

// ModCleared reports if the "mod" edge to the Mod entity was cleared.
func (m *PakMutation) ModCleared() bool {
	return m.clearedmod
}

// ModID returns the "mod" edge ID in the mutation.
func (m *PakMutation) ModID() (id int, exists bool) {
	if m.mod != nil {
		return *m.mod, true
	}
	return
}

// ModIDs returns the "mod" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// ModID instead. It exists only for internal usage by the builders.
func (m *PakMutation) ModIDs() (ids []int) {
	if id := m.mod; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetMod resets all changes to the "mod" edge.
func (m *PakMutation) ResetMod() {
	m.mod = nil
	m.clearedmod = false
}

// Where appends a list predicates to the PakMutation builder.
func (m *PakMutation) Where(ps ...predicate.Pak) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the PakMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *PakMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Pak, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *PakMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *PakMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Pak).
func (m *PakMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *PakMutation) Fields() []string {
	fields := make([]string, 0, 2)
	if m.name != nil {
		fields = append(fields, pak.FieldName)
	}
	if m.installed != nil {
		fields = append(fields, pak.FieldInstalled)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *PakMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case pak.FieldName:
		return m.Name()
	case pak.FieldInstalled:
		return m.Installed()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *PakMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case pak.FieldName:
		return m.OldName(ctx)
	case pak.FieldInstalled:
		return m.OldInstalled(ctx)
	}
	return nil, fmt.Errorf("unknown Pak field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *PakMutation) SetField(name string, value ent.Value) error {
	switch name {
	case pak.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case pak.FieldInstalled:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetInstalled(v)
		return nil
	}
	return fmt.Errorf("unknown Pak field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *PakMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *PakMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *PakMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Pak numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *PakMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *PakMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *PakMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Pak nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *PakMutation) ResetField(name string) error {
	switch name {
	case pak.FieldName:
		m.ResetName()
		return nil
	case pak.FieldInstalled:
		m.ResetInstalled()
		return nil
	}
	return fmt.Errorf("unknown Pak field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *PakMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.mod != nil {
		edges = append(edges, pak.EdgeMod)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *PakMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case pak.EdgeMod:
		if id := m.mod; id != nil {
			return []ent.Value{*id}
		}
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *PakMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *PakMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *PakMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedmod {
		edges = append(edges, pak.EdgeMod)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *PakMutation) EdgeCleared(name string) bool {
	switch name {
	case pak.EdgeMod:
		return m.clearedmod
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *PakMutation) ClearEdge(name string) error {
	switch name {
	case pak.EdgeMod:
		m.ClearMod()
		return nil
	}
	return fmt.Errorf("unknown Pak unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *PakMutation) ResetEdge(name string) error {
	switch name {
	case pak.EdgeMod:
		m.ResetMod()
		return nil
	}
	return fmt.Errorf("unknown Pak edge %s", name)
}
