// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/jbarzegar/ron-mod-manager/ent/mod"
	"github.com/jbarzegar/ron-mod-manager/ent/pak"
)

// Pak is the model entity for the Pak schema.
type Pak struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Installed holds the value of the "installed" field.
	Installed bool `json:"installed,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PakQuery when eager-loading is set.
	Edges        PakEdges `json:"edges"`
	mod_paks     *int
	selectValues sql.SelectValues
}

// PakEdges holds the relations/edges for other nodes in the graph.
type PakEdges struct {
	// Mod holds the value of the mod edge.
	Mod *Mod `json:"mod,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ModOrErr returns the Mod value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PakEdges) ModOrErr() (*Mod, error) {
	if e.loadedTypes[0] {
		if e.Mod == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: mod.Label}
		}
		return e.Mod, nil
	}
	return nil, &NotLoadedError{edge: "mod"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Pak) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case pak.FieldInstalled:
			values[i] = new(sql.NullBool)
		case pak.FieldID:
			values[i] = new(sql.NullInt64)
		case pak.FieldName:
			values[i] = new(sql.NullString)
		case pak.ForeignKeys[0]: // mod_paks
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Pak fields.
func (pa *Pak) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case pak.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			pa.ID = int(value.Int64)
		case pak.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				pa.Name = value.String
			}
		case pak.FieldInstalled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field installed", values[i])
			} else if value.Valid {
				pa.Installed = value.Bool
			}
		case pak.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field mod_paks", value)
			} else if value.Valid {
				pa.mod_paks = new(int)
				*pa.mod_paks = int(value.Int64)
			}
		default:
			pa.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Pak.
// This includes values selected through modifiers, order, etc.
func (pa *Pak) Value(name string) (ent.Value, error) {
	return pa.selectValues.Get(name)
}

// QueryMod queries the "mod" edge of the Pak entity.
func (pa *Pak) QueryMod() *ModQuery {
	return NewPakClient(pa.config).QueryMod(pa)
}

// Update returns a builder for updating this Pak.
// Note that you need to call Pak.Unwrap() before calling this method if this Pak
// was returned from a transaction, and the transaction was committed or rolled back.
func (pa *Pak) Update() *PakUpdateOne {
	return NewPakClient(pa.config).UpdateOne(pa)
}

// Unwrap unwraps the Pak entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (pa *Pak) Unwrap() *Pak {
	_tx, ok := pa.config.driver.(*txDriver)
	if !ok {
		panic("ent: Pak is not a transactional entity")
	}
	pa.config.driver = _tx.drv
	return pa
}

// String implements the fmt.Stringer.
func (pa *Pak) String() string {
	var builder strings.Builder
	builder.WriteString("Pak(")
	builder.WriteString(fmt.Sprintf("id=%v, ", pa.ID))
	builder.WriteString("name=")
	builder.WriteString(pa.Name)
	builder.WriteString(", ")
	builder.WriteString("installed=")
	builder.WriteString(fmt.Sprintf("%v", pa.Installed))
	builder.WriteByte(')')
	return builder.String()
}

// Paks is a parsable slice of Pak.
type Paks []*Pak
