// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/jbarzegar/ron-mod-manager/ent/mod"
	"github.com/jbarzegar/ron-mod-manager/ent/pak"
	"github.com/jbarzegar/ron-mod-manager/ent/predicate"
)

// PakUpdate is the builder for updating Pak entities.
type PakUpdate struct {
	config
	hooks    []Hook
	mutation *PakMutation
}

// Where appends a list predicates to the PakUpdate builder.
func (pu *PakUpdate) Where(ps ...predicate.Pak) *PakUpdate {
	pu.mutation.Where(ps...)
	return pu
}

// SetName sets the "name" field.
func (pu *PakUpdate) SetName(s string) *PakUpdate {
	pu.mutation.SetName(s)
	return pu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (pu *PakUpdate) SetNillableName(s *string) *PakUpdate {
	if s != nil {
		pu.SetName(*s)
	}
	return pu
}

// SetInstalled sets the "installed" field.
func (pu *PakUpdate) SetInstalled(b bool) *PakUpdate {
	pu.mutation.SetInstalled(b)
	return pu
}

// SetNillableInstalled sets the "installed" field if the given value is not nil.
func (pu *PakUpdate) SetNillableInstalled(b *bool) *PakUpdate {
	if b != nil {
		pu.SetInstalled(*b)
	}
	return pu
}

// SetModID sets the "mod" edge to the Mod entity by ID.
func (pu *PakUpdate) SetModID(id int) *PakUpdate {
	pu.mutation.SetModID(id)
	return pu
}

// SetNillableModID sets the "mod" edge to the Mod entity by ID if the given value is not nil.
func (pu *PakUpdate) SetNillableModID(id *int) *PakUpdate {
	if id != nil {
		pu = pu.SetModID(*id)
	}
	return pu
}

// SetMod sets the "mod" edge to the Mod entity.
func (pu *PakUpdate) SetMod(m *Mod) *PakUpdate {
	return pu.SetModID(m.ID)
}

// Mutation returns the PakMutation object of the builder.
func (pu *PakUpdate) Mutation() *PakMutation {
	return pu.mutation
}

// ClearMod clears the "mod" edge to the Mod entity.
func (pu *PakUpdate) ClearMod() *PakUpdate {
	pu.mutation.ClearMod()
	return pu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (pu *PakUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, pu.sqlSave, pu.mutation, pu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (pu *PakUpdate) SaveX(ctx context.Context) int {
	affected, err := pu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (pu *PakUpdate) Exec(ctx context.Context) error {
	_, err := pu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pu *PakUpdate) ExecX(ctx context.Context) {
	if err := pu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (pu *PakUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(pak.Table, pak.Columns, sqlgraph.NewFieldSpec(pak.FieldID, field.TypeInt))
	if ps := pu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pu.mutation.Name(); ok {
		_spec.SetField(pak.FieldName, field.TypeString, value)
	}
	if value, ok := pu.mutation.Installed(); ok {
		_spec.SetField(pak.FieldInstalled, field.TypeBool, value)
	}
	if pu.mutation.ModCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pak.ModTable,
			Columns: []string{pak.ModColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mod.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.ModIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pak.ModTable,
			Columns: []string{pak.ModColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mod.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, pu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pak.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	pu.mutation.done = true
	return n, nil
}

// PakUpdateOne is the builder for updating a single Pak entity.
type PakUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PakMutation
}

// SetName sets the "name" field.
func (puo *PakUpdateOne) SetName(s string) *PakUpdateOne {
	puo.mutation.SetName(s)
	return puo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (puo *PakUpdateOne) SetNillableName(s *string) *PakUpdateOne {
	if s != nil {
		puo.SetName(*s)
	}
	return puo
}

// SetInstalled sets the "installed" field.
func (puo *PakUpdateOne) SetInstalled(b bool) *PakUpdateOne {
	puo.mutation.SetInstalled(b)
	return puo
}

// SetNillableInstalled sets the "installed" field if the given value is not nil.
func (puo *PakUpdateOne) SetNillableInstalled(b *bool) *PakUpdateOne {
	if b != nil {
		puo.SetInstalled(*b)
	}
	return puo
}

// SetModID sets the "mod" edge to the Mod entity by ID.
func (puo *PakUpdateOne) SetModID(id int) *PakUpdateOne {
	puo.mutation.SetModID(id)
	return puo
}

// SetNillableModID sets the "mod" edge to the Mod entity by ID if the given value is not nil.
func (puo *PakUpdateOne) SetNillableModID(id *int) *PakUpdateOne {
	if id != nil {
		puo = puo.SetModID(*id)
	}
	return puo
}

// SetMod sets the "mod" edge to the Mod entity.
func (puo *PakUpdateOne) SetMod(m *Mod) *PakUpdateOne {
	return puo.SetModID(m.ID)
}

// Mutation returns the PakMutation object of the builder.
func (puo *PakUpdateOne) Mutation() *PakMutation {
	return puo.mutation
}

// ClearMod clears the "mod" edge to the Mod entity.
func (puo *PakUpdateOne) ClearMod() *PakUpdateOne {
	puo.mutation.ClearMod()
	return puo
}

// Where appends a list predicates to the PakUpdate builder.
func (puo *PakUpdateOne) Where(ps ...predicate.Pak) *PakUpdateOne {
	puo.mutation.Where(ps...)
	return puo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (puo *PakUpdateOne) Select(field string, fields ...string) *PakUpdateOne {
	puo.fields = append([]string{field}, fields...)
	return puo
}

// Save executes the query and returns the updated Pak entity.
func (puo *PakUpdateOne) Save(ctx context.Context) (*Pak, error) {
	return withHooks(ctx, puo.sqlSave, puo.mutation, puo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (puo *PakUpdateOne) SaveX(ctx context.Context) *Pak {
	node, err := puo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (puo *PakUpdateOne) Exec(ctx context.Context) error {
	_, err := puo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (puo *PakUpdateOne) ExecX(ctx context.Context) {
	if err := puo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (puo *PakUpdateOne) sqlSave(ctx context.Context) (_node *Pak, err error) {
	_spec := sqlgraph.NewUpdateSpec(pak.Table, pak.Columns, sqlgraph.NewFieldSpec(pak.FieldID, field.TypeInt))
	id, ok := puo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Pak.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := puo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, pak.FieldID)
		for _, f := range fields {
			if !pak.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != pak.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := puo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := puo.mutation.Name(); ok {
		_spec.SetField(pak.FieldName, field.TypeString, value)
	}
	if value, ok := puo.mutation.Installed(); ok {
		_spec.SetField(pak.FieldInstalled, field.TypeBool, value)
	}
	if puo.mutation.ModCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pak.ModTable,
			Columns: []string{pak.ModColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mod.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.ModIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pak.ModTable,
			Columns: []string{pak.ModColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mod.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Pak{config: puo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, puo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pak.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	puo.mutation.done = true
	return _node, nil
}
