// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/jbarzegar/ron-mod-manager/ent/mod"
	"github.com/jbarzegar/ron-mod-manager/ent/pak"
)

// PakCreate is the builder for creating a Pak entity.
type PakCreate struct {
	config
	mutation *PakMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (pc *PakCreate) SetName(s string) *PakCreate {
	pc.mutation.SetName(s)
	return pc
}

// SetInstalled sets the "installed" field.
func (pc *PakCreate) SetInstalled(b bool) *PakCreate {
	pc.mutation.SetInstalled(b)
	return pc
}

// SetNillableInstalled sets the "installed" field if the given value is not nil.
func (pc *PakCreate) SetNillableInstalled(b *bool) *PakCreate {
	if b != nil {
		pc.SetInstalled(*b)
	}
	return pc
}

// SetModID sets the "mod" edge to the Mod entity by ID.
func (pc *PakCreate) SetModID(id int) *PakCreate {
	pc.mutation.SetModID(id)
	return pc
}

// SetNillableModID sets the "mod" edge to the Mod entity by ID if the given value is not nil.
func (pc *PakCreate) SetNillableModID(id *int) *PakCreate {
	if id != nil {
		pc = pc.SetModID(*id)
	}
	return pc
}

// SetMod sets the "mod" edge to the Mod entity.
func (pc *PakCreate) SetMod(m *Mod) *PakCreate {
	return pc.SetModID(m.ID)
}

// Mutation returns the PakMutation object of the builder.
func (pc *PakCreate) Mutation() *PakMutation {
	return pc.mutation
}

// Save creates the Pak in the database.
func (pc *PakCreate) Save(ctx context.Context) (*Pak, error) {
	pc.defaults()
	return withHooks(ctx, pc.sqlSave, pc.mutation, pc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (pc *PakCreate) SaveX(ctx context.Context) *Pak {
	v, err := pc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pc *PakCreate) Exec(ctx context.Context) error {
	_, err := pc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pc *PakCreate) ExecX(ctx context.Context) {
	if err := pc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pc *PakCreate) defaults() {
	if _, ok := pc.mutation.Installed(); !ok {
		v := pak.DefaultInstalled
		pc.mutation.SetInstalled(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pc *PakCreate) check() error {
	if _, ok := pc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Pak.name"`)}
	}
	if _, ok := pc.mutation.Installed(); !ok {
		return &ValidationError{Name: "installed", err: errors.New(`ent: missing required field "Pak.installed"`)}
	}
	return nil
}

func (pc *PakCreate) sqlSave(ctx context.Context) (*Pak, error) {
	if err := pc.check(); err != nil {
		return nil, err
	}
	_node, _spec := pc.createSpec()
	if err := sqlgraph.CreateNode(ctx, pc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	pc.mutation.id = &_node.ID
	pc.mutation.done = true
	return _node, nil
}

func (pc *PakCreate) createSpec() (*Pak, *sqlgraph.CreateSpec) {
	var (
		_node = &Pak{config: pc.config}
		_spec = sqlgraph.NewCreateSpec(pak.Table, sqlgraph.NewFieldSpec(pak.FieldID, field.TypeInt))
	)
	if value, ok := pc.mutation.Name(); ok {
		_spec.SetField(pak.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := pc.mutation.Installed(); ok {
		_spec.SetField(pak.FieldInstalled, field.TypeBool, value)
		_node.Installed = value
	}
	if nodes := pc.mutation.ModIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pak.ModTable,
			Columns: []string{pak.ModColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mod.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.mod_paks = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PakCreateBulk is the builder for creating many Pak entities in bulk.
type PakCreateBulk struct {
	config
	err      error
	builders []*PakCreate
}

// Save creates the Pak entities in the database.
func (pcb *PakCreateBulk) Save(ctx context.Context) ([]*Pak, error) {
	if pcb.err != nil {
		return nil, pcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(pcb.builders))
	nodes := make([]*Pak, len(pcb.builders))
	mutators := make([]Mutator, len(pcb.builders))
	for i := range pcb.builders {
		func(i int, root context.Context) {
			builder := pcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PakMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, pcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, pcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, pcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (pcb *PakCreateBulk) SaveX(ctx context.Context) []*Pak {
	v, err := pcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pcb *PakCreateBulk) Exec(ctx context.Context) error {
	_, err := pcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pcb *PakCreateBulk) ExecX(ctx context.Context) {
	if err := pcb.Exec(ctx); err != nil {
		panic(err)
	}
}
