// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/jbarzegar/ron-mod-manager/ent/archive"
	"github.com/jbarzegar/ron-mod-manager/ent/mod"
	"github.com/jbarzegar/ron-mod-manager/ent/pak"
	"github.com/jbarzegar/ron-mod-manager/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	archiveFields := schema.Archive{}.Fields()
	_ = archiveFields
	// archiveDescInstalled is the schema descriptor for installed field.
	archiveDescInstalled := archiveFields[3].Descriptor()
	// archive.DefaultInstalled holds the default value on creation for the installed field.
	archive.DefaultInstalled = archiveDescInstalled.Default.(bool)
	modFields := schema.Mod{}.Fields()
	_ = modFields
	// modDescState is the schema descriptor for state field.
	modDescState := modFields[1].Descriptor()
	// mod.StateValidator is a validator for the "state" field. It is called by the builders before save.
	mod.StateValidator = modDescState.Validators[0].(func(string) error)
	pakFields := schema.Pak{}.Fields()
	_ = pakFields
	// pakDescInstalled is the schema descriptor for installed field.
	pakDescInstalled := pakFields[1].Descriptor()
	// pak.DefaultInstalled holds the default value on creation for the installed field.
	pak.DefaultInstalled = pakDescInstalled.Default.(bool)
}
