// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ArchivesColumns holds the columns for the "archives" table.
	ArchivesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "archive_path", Type: field.TypeString, Unique: true},
		{Name: "md5sum", Type: field.TypeString},
		{Name: "installed", Type: field.TypeBool, Default: false},
	}
	// ArchivesTable holds the schema information for the "archives" table.
	ArchivesTable = &schema.Table{
		Name:       "archives",
		Columns:    ArchivesColumns,
		PrimaryKey: []*schema.Column{ArchivesColumns[0]},
	}
	// ModsColumns holds the columns for the "mods" table.
	ModsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "state", Type: field.TypeString},
		{Name: "mod_archive", Type: field.TypeInt},
	}
	// ModsTable holds the schema information for the "mods" table.
	ModsTable = &schema.Table{
		Name:       "mods",
		Columns:    ModsColumns,
		PrimaryKey: []*schema.Column{ModsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "mods_archives_archive",
				Columns:    []*schema.Column{ModsColumns[3]},
				RefColumns: []*schema.Column{ArchivesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// PaksColumns holds the columns for the "paks" table.
	PaksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "installed", Type: field.TypeBool, Default: false},
		{Name: "mod_paks", Type: field.TypeInt, Nullable: true},
	}
	// PaksTable holds the schema information for the "paks" table.
	PaksTable = &schema.Table{
		Name:       "paks",
		Columns:    PaksColumns,
		PrimaryKey: []*schema.Column{PaksColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "paks_mods_paks",
				Columns:    []*schema.Column{PaksColumns[3]},
				RefColumns: []*schema.Column{ModsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ArchivesTable,
		ModsTable,
		PaksTable,
	}
)

func init() {
	ModsTable.ForeignKeys[0].RefTable = ArchivesTable
	PaksTable.ForeignKeys[0].RefTable = ModsTable
}
