// Code generated by ent, DO NOT EDIT.

package mod

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the mod type in the database.
	Label = "mod"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldState holds the string denoting the state field in the database.
	FieldState = "state"
	// EdgeArchive holds the string denoting the archive edge name in mutations.
	EdgeArchive = "archive"
	// EdgePaks holds the string denoting the paks edge name in mutations.
	EdgePaks = "paks"
	// Table holds the table name of the mod in the database.
	Table = "mods"
	// ArchiveTable is the table that holds the archive relation/edge.
	ArchiveTable = "mods"
	// ArchiveInverseTable is the table name for the Archive entity.
	// It exists in this package in order to avoid circular dependency with the "archive" package.
	ArchiveInverseTable = "archives"
	// ArchiveColumn is the table column denoting the archive relation/edge.
	ArchiveColumn = "mod_archive"
	// PaksTable is the table that holds the paks relation/edge.
	PaksTable = "paks"
	// PaksInverseTable is the table name for the Pak entity.
	// It exists in this package in order to avoid circular dependency with the "pak" package.
	PaksInverseTable = "paks"
	// PaksColumn is the table column denoting the paks relation/edge.
	PaksColumn = "mod_paks"
)

// Columns holds all SQL columns for mod fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldState,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "mods"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"mod_archive",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// StateValidator is a validator for the "state" field. It is called by the builders before save.
	StateValidator func(string) error
)

// OrderOption defines the ordering options for the Mod queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByState orders the results by the state field.
func ByState(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldState, opts...).ToFunc()
}

// ByArchiveField orders the results by archive field.
func ByArchiveField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newArchiveStep(), sql.OrderByField(field, opts...))
	}
}

// ByPaksCount orders the results by paks count.
func ByPaksCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newPaksStep(), opts...)
	}
}

// ByPaks orders the results by paks terms.
func ByPaks(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPaksStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newArchiveStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ArchiveInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, ArchiveTable, ArchiveColumn),
	)
}
func newPaksStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PaksInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, PaksTable, PaksColumn),
	)
}
