// Code generated by ent, DO NOT EDIT.

package archive

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the archive type in the database.
	Label = "archive"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldArchivePath holds the string denoting the archivepath field in the database.
	FieldArchivePath = "archive_path"
	// FieldMd5Sum holds the string denoting the md5sum field in the database.
	FieldMd5Sum = "md5sum"
	// FieldInstalled holds the string denoting the installed field in the database.
	FieldInstalled = "installed"
	// Table holds the table name of the archive in the database.
	Table = "archives"
)

// Columns holds all SQL columns for archive fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldArchivePath,
	FieldMd5Sum,
	FieldInstalled,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultInstalled holds the default value on creation for the "installed" field.
	DefaultInstalled bool
)

// OrderOption defines the ordering options for the Archive queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByArchivePath orders the results by the archivePath field.
func ByArchivePath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldArchivePath, opts...).ToFunc()
}

// ByMd5Sum orders the results by the md5Sum field.
func ByMd5Sum(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMd5Sum, opts...).ToFunc()
}

// ByInstalled orders the results by the installed field.
func ByInstalled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInstalled, opts...).ToFunc()
}
