// Code generated by ent, DO NOT EDIT.

package archive

import (
	"entgo.io/ent/dialect/sql"
	"github.com/jbarzegar/ron-mod-manager/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Archive {
	return predicate.Archive(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Archive {
	return predicate.Archive(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Archive {
	return predicate.Archive(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Archive {
	return predicate.Archive(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Archive {
	return predicate.Archive(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Archive {
	return predicate.Archive(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Archive {
	return predicate.Archive(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Archive {
	return predicate.Archive(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Archive {
	return predicate.Archive(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Archive {
	return predicate.Archive(sql.FieldEQ(FieldName, v))
}

// ArchivePath applies equality check predicate on the "archivePath" field. It's identical to ArchivePathEQ.
func ArchivePath(v string) predicate.Archive {
	return predicate.Archive(sql.FieldEQ(FieldArchivePath, v))
}

// Md5Sum applies equality check predicate on the "md5Sum" field. It's identical to Md5SumEQ.
func Md5Sum(v string) predicate.Archive {
	return predicate.Archive(sql.FieldEQ(FieldMd5Sum, v))
}

// Installed applies equality check predicate on the "installed" field. It's identical to InstalledEQ.
func Installed(v bool) predicate.Archive {
	return predicate.Archive(sql.FieldEQ(FieldInstalled, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Archive {
	return predicate.Archive(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Archive {
	return predicate.Archive(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Archive {
	return predicate.Archive(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Archive {
	return predicate.Archive(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Archive {
	return predicate.Archive(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Archive {
	return predicate.Archive(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Archive {
	return predicate.Archive(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Archive {
	return predicate.Archive(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Archive {
	return predicate.Archive(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Archive {
	return predicate.Archive(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Archive {
	return predicate.Archive(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Archive {
	return predicate.Archive(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Archive {
	return predicate.Archive(sql.FieldContainsFold(FieldName, v))
}

// ArchivePathEQ applies the EQ predicate on the "archivePath" field.
func ArchivePathEQ(v string) predicate.Archive {
	return predicate.Archive(sql.FieldEQ(FieldArchivePath, v))
}

// ArchivePathNEQ applies the NEQ predicate on the "archivePath" field.
func ArchivePathNEQ(v string) predicate.Archive {
	return predicate.Archive(sql.FieldNEQ(FieldArchivePath, v))
}

// ArchivePathIn applies the In predicate on the "archivePath" field.
func ArchivePathIn(vs ...string) predicate.Archive {
	return predicate.Archive(sql.FieldIn(FieldArchivePath, vs...))
}

// ArchivePathNotIn applies the NotIn predicate on the "archivePath" field.
func ArchivePathNotIn(vs ...string) predicate.Archive {
	return predicate.Archive(sql.FieldNotIn(FieldArchivePath, vs...))
}

// ArchivePathGT applies the GT predicate on the "archivePath" field.
func ArchivePathGT(v string) predicate.Archive {
	return predicate.Archive(sql.FieldGT(FieldArchivePath, v))
}

// ArchivePathGTE applies the GTE predicate on the "archivePath" field.
func ArchivePathGTE(v string) predicate.Archive {
	return predicate.Archive(sql.FieldGTE(FieldArchivePath, v))
}

// ArchivePathLT applies the LT predicate on the "archivePath" field.
func ArchivePathLT(v string) predicate.Archive {
	return predicate.Archive(sql.FieldLT(FieldArchivePath, v))
}

// ArchivePathLTE applies the LTE predicate on the "archivePath" field.
func ArchivePathLTE(v string) predicate.Archive {
	return predicate.Archive(sql.FieldLTE(FieldArchivePath, v))
}

// ArchivePathContains applies the Contains predicate on the "archivePath" field.
func ArchivePathContains(v string) predicate.Archive {
	return predicate.Archive(sql.FieldContains(FieldArchivePath, v))
}

// ArchivePathHasPrefix applies the HasPrefix predicate on the "archivePath" field.
func ArchivePathHasPrefix(v string) predicate.Archive {
	return predicate.Archive(sql.FieldHasPrefix(FieldArchivePath, v))
}

// ArchivePathHasSuffix applies the HasSuffix predicate on the "archivePath" field.
func ArchivePathHasSuffix(v string) predicate.Archive {
	return predicate.Archive(sql.FieldHasSuffix(FieldArchivePath, v))
}

// ArchivePathEqualFold applies the EqualFold predicate on the "archivePath" field.
func ArchivePathEqualFold(v string) predicate.Archive {
	return predicate.Archive(sql.FieldEqualFold(FieldArchivePath, v))
}

// ArchivePathContainsFold applies the ContainsFold predicate on the "archivePath" field.
func ArchivePathContainsFold(v string) predicate.Archive {
	return predicate.Archive(sql.FieldContainsFold(FieldArchivePath, v))
}

// Md5SumEQ applies the EQ predicate on the "md5Sum" field.
func Md5SumEQ(v string) predicate.Archive {
	return predicate.Archive(sql.FieldEQ(FieldMd5Sum, v))
}

// Md5SumNEQ applies the NEQ predicate on the "md5Sum" field.
func Md5SumNEQ(v string) predicate.Archive {
	return predicate.Archive(sql.FieldNEQ(FieldMd5Sum, v))
}

// Md5SumIn applies the In predicate on the "md5Sum" field.
func Md5SumIn(vs ...string) predicate.Archive {
	return predicate.Archive(sql.FieldIn(FieldMd5Sum, vs...))
}

// Md5SumNotIn applies the NotIn predicate on the "md5Sum" field.
func Md5SumNotIn(vs ...string) predicate.Archive {
	return predicate.Archive(sql.FieldNotIn(FieldMd5Sum, vs...))
}

// Md5SumGT applies the GT predicate on the "md5Sum" field.
func Md5SumGT(v string) predicate.Archive {
	return predicate.Archive(sql.FieldGT(FieldMd5Sum, v))
}

// Md5SumGTE applies the GTE predicate on the "md5Sum" field.
func Md5SumGTE(v string) predicate.Archive {
	return predicate.Archive(sql.FieldGTE(FieldMd5Sum, v))
}

// Md5SumLT applies the LT predicate on the "md5Sum" field.
func Md5SumLT(v string) predicate.Archive {
	return predicate.Archive(sql.FieldLT(FieldMd5Sum, v))
}

// Md5SumLTE applies the LTE predicate on the "md5Sum" field.
func Md5SumLTE(v string) predicate.Archive {
	return predicate.Archive(sql.FieldLTE(FieldMd5Sum, v))
}

// Md5SumContains applies the Contains predicate on the "md5Sum" field.
func Md5SumContains(v string) predicate.Archive {
	return predicate.Archive(sql.FieldContains(FieldMd5Sum, v))
}

// Md5SumHasPrefix applies the HasPrefix predicate on the "md5Sum" field.
func Md5SumHasPrefix(v string) predicate.Archive {
	return predicate.Archive(sql.FieldHasPrefix(FieldMd5Sum, v))
}

// Md5SumHasSuffix applies the HasSuffix predicate on the "md5Sum" field.
func Md5SumHasSuffix(v string) predicate.Archive {
	return predicate.Archive(sql.FieldHasSuffix(FieldMd5Sum, v))
}

// Md5SumEqualFold applies the EqualFold predicate on the "md5Sum" field.
func Md5SumEqualFold(v string) predicate.Archive {
	return predicate.Archive(sql.FieldEqualFold(FieldMd5Sum, v))
}

// Md5SumContainsFold applies the ContainsFold predicate on the "md5Sum" field.
func Md5SumContainsFold(v string) predicate.Archive {
	return predicate.Archive(sql.FieldContainsFold(FieldMd5Sum, v))
}

// InstalledEQ applies the EQ predicate on the "installed" field.
func InstalledEQ(v bool) predicate.Archive {
	return predicate.Archive(sql.FieldEQ(FieldInstalled, v))
}

// InstalledNEQ applies the NEQ predicate on the "installed" field.
func InstalledNEQ(v bool) predicate.Archive {
	return predicate.Archive(sql.FieldNEQ(FieldInstalled, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Archive) predicate.Archive {
	return predicate.Archive(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Archive) predicate.Archive {
	return predicate.Archive(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Archive) predicate.Archive {
	return predicate.Archive(sql.NotPredicates(p))
}
